//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenparcialventas
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasLibros
    {
        public int ID { get; set; }
        public string GeneroCliente { get; set; }
        public Nullable<int> TipoLibro { get; set; }
        public Nullable<int> Cantidad { get; set; }
    }
}
